/*
 * Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Kochnev.Auth.Private.Client.Client;
using Kochnev.Auth.Private.Client.Model;

namespace Kochnev.Auth.Private.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoginCallbackApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackAcceptRequest"> (optional)</param>
        /// <returns>ApiApiPrivateLoginCallbackAcceptResponse</returns>
        ApiApiPrivateLoginCallbackAcceptResponse ApiPrivateLoginCallbackAcceptPost(ApiApiPrivateLoginCallbackAcceptRequest? apiApiPrivateLoginCallbackAcceptRequest = default(ApiApiPrivateLoginCallbackAcceptRequest?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackAcceptRequest"> (optional)</param>
        /// <returns>ApiResponse of ApiApiPrivateLoginCallbackAcceptResponse</returns>
        ApiResponse<ApiApiPrivateLoginCallbackAcceptResponse> ApiPrivateLoginCallbackAcceptPostWithHttpInfo(ApiApiPrivateLoginCallbackAcceptRequest? apiApiPrivateLoginCallbackAcceptRequest = default(ApiApiPrivateLoginCallbackAcceptRequest?));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackRejectRequest"> (optional)</param>
        /// <returns>ApiApiPrivateLoginCallbackRejectResponse</returns>
        ApiApiPrivateLoginCallbackRejectResponse ApiPrivateLoginCallbackRejectPost(ApiApiPrivateLoginCallbackRejectRequest? apiApiPrivateLoginCallbackRejectRequest = default(ApiApiPrivateLoginCallbackRejectRequest?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackRejectRequest"> (optional)</param>
        /// <returns>ApiResponse of ApiApiPrivateLoginCallbackRejectResponse</returns>
        ApiResponse<ApiApiPrivateLoginCallbackRejectResponse> ApiPrivateLoginCallbackRejectPostWithHttpInfo(ApiApiPrivateLoginCallbackRejectRequest? apiApiPrivateLoginCallbackRejectRequest = default(ApiApiPrivateLoginCallbackRejectRequest?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoginCallbackApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackAcceptRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiApiPrivateLoginCallbackAcceptResponse</returns>
        System.Threading.Tasks.Task<ApiApiPrivateLoginCallbackAcceptResponse> ApiPrivateLoginCallbackAcceptPostAsync(ApiApiPrivateLoginCallbackAcceptRequest? apiApiPrivateLoginCallbackAcceptRequest = default(ApiApiPrivateLoginCallbackAcceptRequest?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackAcceptRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ApiApiPrivateLoginCallbackAcceptResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiApiPrivateLoginCallbackAcceptResponse>> ApiPrivateLoginCallbackAcceptPostWithHttpInfoAsync(ApiApiPrivateLoginCallbackAcceptRequest? apiApiPrivateLoginCallbackAcceptRequest = default(ApiApiPrivateLoginCallbackAcceptRequest?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackRejectRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiApiPrivateLoginCallbackRejectResponse</returns>
        System.Threading.Tasks.Task<ApiApiPrivateLoginCallbackRejectResponse> ApiPrivateLoginCallbackRejectPostAsync(ApiApiPrivateLoginCallbackRejectRequest? apiApiPrivateLoginCallbackRejectRequest = default(ApiApiPrivateLoginCallbackRejectRequest?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackRejectRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ApiApiPrivateLoginCallbackRejectResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiApiPrivateLoginCallbackRejectResponse>> ApiPrivateLoginCallbackRejectPostWithHttpInfoAsync(ApiApiPrivateLoginCallbackRejectRequest? apiApiPrivateLoginCallbackRejectRequest = default(ApiApiPrivateLoginCallbackRejectRequest?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoginCallbackApi : ILoginCallbackApiSync, ILoginCallbackApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LoginCallbackApi : IDisposable, ILoginCallbackApi
    {
        private Kochnev.Auth.Private.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LoginCallbackApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public LoginCallbackApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoginCallbackApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public LoginCallbackApi(string basePath)
        {
            this.Configuration = Kochnev.Auth.Private.Client.Client.Configuration.MergeConfigurations(
                Kochnev.Auth.Private.Client.Client.GlobalConfiguration.Instance,
                new Kochnev.Auth.Private.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Kochnev.Auth.Private.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Kochnev.Auth.Private.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoginCallbackApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public LoginCallbackApi(Kochnev.Auth.Private.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Kochnev.Auth.Private.Client.Client.Configuration.MergeConfigurations(
                Kochnev.Auth.Private.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Kochnev.Auth.Private.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Kochnev.Auth.Private.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoginCallbackApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public LoginCallbackApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoginCallbackApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public LoginCallbackApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Kochnev.Auth.Private.Client.Client.Configuration.MergeConfigurations(
                Kochnev.Auth.Private.Client.Client.GlobalConfiguration.Instance,
                new Kochnev.Auth.Private.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Kochnev.Auth.Private.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Kochnev.Auth.Private.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoginCallbackApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public LoginCallbackApi(HttpClient client, Kochnev.Auth.Private.Client.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Kochnev.Auth.Private.Client.Client.Configuration.MergeConfigurations(
                Kochnev.Auth.Private.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Kochnev.Auth.Private.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Kochnev.Auth.Private.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoginCallbackApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public LoginCallbackApi(Kochnev.Auth.Private.Client.Client.ISynchronousClient client, Kochnev.Auth.Private.Client.Client.IAsynchronousClient asyncClient, Kochnev.Auth.Private.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Kochnev.Auth.Private.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Kochnev.Auth.Private.Client.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Kochnev.Auth.Private.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Kochnev.Auth.Private.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Kochnev.Auth.Private.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Kochnev.Auth.Private.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackAcceptRequest"> (optional)</param>
        /// <returns>ApiApiPrivateLoginCallbackAcceptResponse</returns>
        public ApiApiPrivateLoginCallbackAcceptResponse ApiPrivateLoginCallbackAcceptPost(ApiApiPrivateLoginCallbackAcceptRequest? apiApiPrivateLoginCallbackAcceptRequest = default(ApiApiPrivateLoginCallbackAcceptRequest?))
        {
            Kochnev.Auth.Private.Client.Client.ApiResponse<ApiApiPrivateLoginCallbackAcceptResponse> localVarResponse = ApiPrivateLoginCallbackAcceptPostWithHttpInfo(apiApiPrivateLoginCallbackAcceptRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackAcceptRequest"> (optional)</param>
        /// <returns>ApiResponse of ApiApiPrivateLoginCallbackAcceptResponse</returns>
        public Kochnev.Auth.Private.Client.Client.ApiResponse<ApiApiPrivateLoginCallbackAcceptResponse> ApiPrivateLoginCallbackAcceptPostWithHttpInfo(ApiApiPrivateLoginCallbackAcceptRequest? apiApiPrivateLoginCallbackAcceptRequest = default(ApiApiPrivateLoginCallbackAcceptRequest?))
        {
            Kochnev.Auth.Private.Client.Client.RequestOptions localVarRequestOptions = new Kochnev.Auth.Private.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Kochnev.Auth.Private.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Kochnev.Auth.Private.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = apiApiPrivateLoginCallbackAcceptRequest;


            // make the HTTP request
            var localVarResponse = this.Client.Post<ApiApiPrivateLoginCallbackAcceptResponse>("/api/private/login/callback/accept", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPrivateLoginCallbackAcceptPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackAcceptRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiApiPrivateLoginCallbackAcceptResponse</returns>
        public async System.Threading.Tasks.Task<ApiApiPrivateLoginCallbackAcceptResponse> ApiPrivateLoginCallbackAcceptPostAsync(ApiApiPrivateLoginCallbackAcceptRequest? apiApiPrivateLoginCallbackAcceptRequest = default(ApiApiPrivateLoginCallbackAcceptRequest?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Kochnev.Auth.Private.Client.Client.ApiResponse<ApiApiPrivateLoginCallbackAcceptResponse> localVarResponse = await ApiPrivateLoginCallbackAcceptPostWithHttpInfoAsync(apiApiPrivateLoginCallbackAcceptRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackAcceptRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ApiApiPrivateLoginCallbackAcceptResponse)</returns>
        public async System.Threading.Tasks.Task<Kochnev.Auth.Private.Client.Client.ApiResponse<ApiApiPrivateLoginCallbackAcceptResponse>> ApiPrivateLoginCallbackAcceptPostWithHttpInfoAsync(ApiApiPrivateLoginCallbackAcceptRequest? apiApiPrivateLoginCallbackAcceptRequest = default(ApiApiPrivateLoginCallbackAcceptRequest?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Kochnev.Auth.Private.Client.Client.RequestOptions localVarRequestOptions = new Kochnev.Auth.Private.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Kochnev.Auth.Private.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Kochnev.Auth.Private.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = apiApiPrivateLoginCallbackAcceptRequest;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ApiApiPrivateLoginCallbackAcceptResponse>("/api/private/login/callback/accept", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPrivateLoginCallbackAcceptPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackRejectRequest"> (optional)</param>
        /// <returns>ApiApiPrivateLoginCallbackRejectResponse</returns>
        public ApiApiPrivateLoginCallbackRejectResponse ApiPrivateLoginCallbackRejectPost(ApiApiPrivateLoginCallbackRejectRequest? apiApiPrivateLoginCallbackRejectRequest = default(ApiApiPrivateLoginCallbackRejectRequest?))
        {
            Kochnev.Auth.Private.Client.Client.ApiResponse<ApiApiPrivateLoginCallbackRejectResponse> localVarResponse = ApiPrivateLoginCallbackRejectPostWithHttpInfo(apiApiPrivateLoginCallbackRejectRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackRejectRequest"> (optional)</param>
        /// <returns>ApiResponse of ApiApiPrivateLoginCallbackRejectResponse</returns>
        public Kochnev.Auth.Private.Client.Client.ApiResponse<ApiApiPrivateLoginCallbackRejectResponse> ApiPrivateLoginCallbackRejectPostWithHttpInfo(ApiApiPrivateLoginCallbackRejectRequest? apiApiPrivateLoginCallbackRejectRequest = default(ApiApiPrivateLoginCallbackRejectRequest?))
        {
            Kochnev.Auth.Private.Client.Client.RequestOptions localVarRequestOptions = new Kochnev.Auth.Private.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Kochnev.Auth.Private.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Kochnev.Auth.Private.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = apiApiPrivateLoginCallbackRejectRequest;


            // make the HTTP request
            var localVarResponse = this.Client.Post<ApiApiPrivateLoginCallbackRejectResponse>("/api/private/login/callback/reject", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPrivateLoginCallbackRejectPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackRejectRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiApiPrivateLoginCallbackRejectResponse</returns>
        public async System.Threading.Tasks.Task<ApiApiPrivateLoginCallbackRejectResponse> ApiPrivateLoginCallbackRejectPostAsync(ApiApiPrivateLoginCallbackRejectRequest? apiApiPrivateLoginCallbackRejectRequest = default(ApiApiPrivateLoginCallbackRejectRequest?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Kochnev.Auth.Private.Client.Client.ApiResponse<ApiApiPrivateLoginCallbackRejectResponse> localVarResponse = await ApiPrivateLoginCallbackRejectPostWithHttpInfoAsync(apiApiPrivateLoginCallbackRejectRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Kochnev.Auth.Private.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiApiPrivateLoginCallbackRejectRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ApiApiPrivateLoginCallbackRejectResponse)</returns>
        public async System.Threading.Tasks.Task<Kochnev.Auth.Private.Client.Client.ApiResponse<ApiApiPrivateLoginCallbackRejectResponse>> ApiPrivateLoginCallbackRejectPostWithHttpInfoAsync(ApiApiPrivateLoginCallbackRejectRequest? apiApiPrivateLoginCallbackRejectRequest = default(ApiApiPrivateLoginCallbackRejectRequest?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Kochnev.Auth.Private.Client.Client.RequestOptions localVarRequestOptions = new Kochnev.Auth.Private.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Kochnev.Auth.Private.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Kochnev.Auth.Private.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = apiApiPrivateLoginCallbackRejectRequest;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ApiApiPrivateLoginCallbackRejectResponse>("/api/private/login/callback/reject", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPrivateLoginCallbackRejectPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
