name: main

on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release
      - name: Pack
        run: dotnet pack -c Release -o ./dist
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - name: Push
        run: dotnet nuget push ./dist/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
